TimeSyncPro/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from TimeSyncPro.accounts import views as views

urlpatterns = [
    path("api/events/", views.CalendarEventsView.as_view(), name="api_events"),
    path("api/get-working-days/", views.get_working_days, name="get_working_days"),
    path("login/", views.SignInUserView.as_view(), name="sign_in"),
    path("sign-out/", views.LogoutAPIView.as_view(), name="sign_out"),
    path(
        "register/",
        views.SignupCompanyAdministratorView.as_view(),
        name="sign_up_administrator",
    ),
    path("password-reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "activate-set-password/<str:token>/",
        views.ActivateAndSetPasswordView.as_view(),
        name="activate_and_set_password",
    ),
    path(
        "users/<slug:slug>/",
        include(
            [
                path(
                    "create-profile-company/",
                    views.CreateProfileAndCompanyView.as_view(),
                    name="create_profile_company",
                ),
                path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
                path(
                    "profile/",
                    include(
                        [
                            path(
                                "",
                                views.DetailsOwnProfileView.as_view(),
                                name="profile",
                            ),
                            path(
                                "edit/",
                                views.EditProfileDispatcherView.as_view(),
                                name="update_profile",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
]

TimeSyncPro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from TimeSyncPro import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("TimeSyncPro.common.urls")),
    path("", include("TimeSyncPro.accounts.urls")),
    path("", include("TimeSyncPro.companies.urls")),
    path("", include("TimeSyncPro.absences.urls")),
    path("", include("TimeSyncPro.reports.urls")),
    path("", include("TimeSyncPro.shifts.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

TimeSyncPro/accounts/models/profile.py
import datetime
from datetime import timedelta, date

from django.apps import apps
from django.core.validators import MinLengthValidator
from django.db import models
from django.db.models import F

from . import TSPUser

# from .proxy_models import ManagerProxy, HRProxy, TeamLeaderProxy, StaffProxy

from ..validators import IsDigitsValidator, DateRangeValidator, DateOfBirthValidator

from TimeSyncPro.common.model_mixins import CreatedModifiedMixin
from ...history.model_mixins import HistoryMixin


class Profile(HistoryMixin, CreatedModifiedMixin):
    MAX_FIRST_NAME_LENGTH = 30
    MIN_FIRST_NAME_LENGTH = 2
    MAX_LAST_NAME_LENGTH = 30
    MIN_LAST_NAME_LENGTH = 2
    MAX_EMPLOYEE_ID_LENGTH = 15
    MIN_EMPLOYEE_ID_LENGTH = 5
    MAX_PHONE_NUMBER_LENGTH = 15
    MIN_PHONE_NUMBER_LENGTH = 10
    MIN_AGE = 16

    class EmployeeRoles(models.TextChoices):
        STAFF = "Staff", "Staff"
        TEAM_LEADER = "Team Leader", "Team Leader"
        MANAGER = "Manager", "Manager"
        HR = "HR", "HR"

    tracked_fields = [
        "first_name",
        "last_name",
        "employee_id",
        "role",
        "date_of_hire",
        "days_off_left",
        "phone_number",
        "address",
        "date_of_birth",
        "department",
        "manage_department",
        "shift",
        "team",
    ]

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["employee_id", "company"], name="unique_employee_id_per_company"
            )
        ]

        permissions = [
            ("add_company_admin", "Can add Company Administrator"),
            ("change_company_admin", "Can change Company Administrator"),
            ("delete_company_admin", "Can delete Company Administrator"),
            ("view_company_admin", "Can view Company Administrator"),
            ("add_hr", "Can add HR"),
            ("change_hr", "Can change HR"),
            ("delete_hr", "Can delete HR"),
            ("view_hr", "Can view HR"),
            ("add_manager", "Can add Manager"),
            ("change_manager", "Can change Manager"),
            ("delete_manager", "Can delete Manager"),
            ("view_manager", "Can view Manager"),
            ("add_team_leader", "Can add TeamLeader"),
            ("change_team_leader", "Can change TeamLeader"),
            ("delete_team_leader", "Can delete TeamLeader"),
            ("view_team_leader", "Can view TeamLeader"),
            ("add_staff", "Can add Staff"),
            ("change_staff", "Can change Staff"),
            ("delete_staff", "Can delete Staff"),
            ("view_staff", "Can view Staff"),
            ("view_employee", "Can view Employees"),
            ("add_employee", "Can add Employees"),
            ("view_all_employees", "Can view all Employees"),
            ("view_department_employees", "Can view department Employees"),
            ("view_team_employees", "Can view team Employees"),
        ]

    user = models.OneToOneField(
        TSPUser,
        on_delete=models.CASCADE,
        related_name="profile",
        blank=False,
        null=False,
    )

    company = models.ForeignKey(
        "companies.Company",
        on_delete=models.CASCADE,
        related_name="employees",
        blank=True,
        null=True,
    )

    is_company_admin = models.BooleanField(
        default=False,
        blank=True,
        null=False,
    )

    first_name = models.CharField(
        max_length=MAX_FIRST_NAME_LENGTH,
        validators=[MinLengthValidator(MIN_FIRST_NAME_LENGTH)],
        blank=True,
        null=True,
    )

    last_name = models.CharField(
        max_length=MAX_LAST_NAME_LENGTH,
        validators=[MinLengthValidator(MIN_LAST_NAME_LENGTH)],
        blank=True,
        null=True,
    )

    role = models.CharField(
        max_length=max([len(choice) for choice in EmployeeRoles.values]),
        choices=EmployeeRoles.choices,
        # default=EmployeeRoles.STAFF,
        blank=True,
        null=True,
    )

    employee_id = models.CharField(
        max_length=MAX_EMPLOYEE_ID_LENGTH,
        validators=[MinLengthValidator(MIN_EMPLOYEE_ID_LENGTH)],
        blank=True,
        null=True,
    )

    date_of_hire = models.DateField(
        blank=True,
        null=True,
    )

    remaining_leave_days = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
    )

    next_year_leave_days = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
    )

    phone_number = models.CharField(
        max_length=MAX_PHONE_NUMBER_LENGTH,
        validators=[
            MinLengthValidator(MIN_PHONE_NUMBER_LENGTH),
            IsDigitsValidator("Phone number must contain only digits"),
        ],
        blank=True,
        null=True,
    )

    address = models.OneToOneField(
        "common.Address",
        on_delete=models.SET_NULL,
        related_name="employee",
        blank=True,
        null=True,
    )

    date_of_birth = models.DateField(
        validators=[
            DateOfBirthValidator,
        ],
        blank=True,
        null=True,
    )

    profile_picture = models.ImageField(
        upload_to="profile_pictures/",
        blank=True,
        null=True,
    )

    department = models.ForeignKey(
        "companies.Department",
        on_delete=models.SET_NULL,
        related_name="employees",
        blank=True,
        null=True,
    )

    shift = models.ForeignKey(
        "shifts.Shift",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="employees",
    )

    team = models.ForeignKey(
        "companies.Team",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="employees",
    )

    @classmethod
    def get_all_employee_roles(cls):
        employee_role = [role.value for role in cls.EmployeeRoles]
        return employee_role

    @property
    def group_name(self):
        if self.is_company_admin:
            return "Company_Admin"
        return self.role

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_employee_needed_permission_codename(self, action):
        return f"{action}_{self.role.lower().replace(' ', '_')}"

    def set_remaining_leave_days(self, leave_days):
        self.remaining_leave_days = F("remaining_leave_days") - leave_days
        self.save(update_fields=["remaining_leave_days"])

    def set_next_year_leave_days(self, leave_days):
        self.next_year_leave_days = F("next_year_leave_days") - leave_days
        self.save(update_fields=["next_year_leave_days"])

    def __str__(self):
        return f"{self.full_name} - {self.role}"

    def save(self, *args, **kwargs):

        if self.first_name:
            self.first_name = self.format_name(self.first_name)
        if self.last_name:
            self.last_name = self.format_name(self.last_name)

        is_new = not self.pk

        if is_new and not self.user_id:
            super().save(*args, **kwargs, skip_history=True)
            # if self.user_id:
            #     self._create_history("create", {
            #         "user": {"old": None, "new": self.user_id}
            #     })
        else:
            super().save(*args, **kwargs)

    @staticmethod
    def format_name(name):

        if not name:
            return ""

        name = " ".join(name.split())

        return name.title()

    def get_holiday_approver(self):
        if self.team and self.team.holiday_approver:
            return self.team.holiday_approver
        elif self.department and self.department.holiday_approver:
            return self.department.holiday_approver
        return self.company.holiday_approver

    def get_shift(self):
        if self.shift:
            return self.shift
        elif self.team and self.team.shift:
            return self.team.shift

    def get_team(self):
        if self.team:
            return self.team
        return None

    def get_working_days(self, start_date, end_date):
        shift = self.get_shift()
        if shift:
            return shift.get_shift_working_dates_by_period(start_date, end_date)

        working_days = []
        current_date = start_date
        while current_date <= end_date:
            if current_date.weekday() < 5:
                working_days.append(current_date)
            current_date += timedelta(days=1)
        return working_days

    def get_working_days_with_time(self, start_date, end_date):
        shift = self.get_shift()
        if shift:
            return shift.get_shift_working_dates_with_time_by_period(
                start_date, end_date
            )

        working_days = {}
        start_time = datetime.time(9, 0)
        end_time = datetime.time(17, 0)

        current_date = start_date
        while current_date <= end_date:
            if current_date.weekday() < 5:
                working_days[current_date] = {
                    "start_time": start_time,
                    "end_time": end_time,
                }
            current_date += timedelta(days=1)
        return working_days

    def get_days_off(self, start_date, end_date):
        working_days = self.get_working_days(start_date, end_date)
        all_days = [
            start_date + timedelta(days=i)
            for i in range((end_date - start_date).days + 1)
        ]
        return [day for day in all_days if day not in working_days]

    def get_team_employees_holidays_at_a_time(self):
        if hasattr(self, "team") and self.team:
            return self.team.employees_holidays_at_a_time
        return None

    def get_count_of_working_days_by_period(self, start_date, end_date):
        working_days = 0
        shift = self.get_shift()
        if shift:
            return shift.get_count_of_shift_working_days_by_period(start_date, end_date)

        current_date = start_date
        while current_date <= end_date:

            if current_date.weekday() < 5:

TimeSyncPro/accounts/forms/create_profile_form.py
import logging
from django import forms
from django.contrib.auth import get_user_model
from ..form_mixins import RequiredFieldsFormMixin
from ..models import Profile


logger = logging.getLogger(__name__)

UserModel = get_user_model()


class CrateProfileBaseForm(RequiredFieldsFormMixin, forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ["user", "company", "is_company_admin"]

        widgets = {
            "date_of_hire": forms.DateInput(attrs={"type": "date"}),
            "date_of_birth": forms.DateInput(attrs={"type": "date"}),
        }


class CreateCompanyAdministratorProfileForm(CrateProfileBaseForm):
    class Meta(CrateProfileBaseForm.Meta):
        exclude = CrateProfileBaseForm.Meta.exclude + [
            "department",
            "manages_departments",
            "team",
            "shift",
            "address",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'] = forms.ChoiceField(
            choices=[
                (Profile.EmployeeRoles.HR, 'HR'),
                (Profile.EmployeeRoles.MANAGER, 'Manager'),
            ]
        )

TimeSyncPro/accounts/forms/custom_set_password_form.py
from django import forms
from django.contrib.auth.forms import SetPasswordForm


class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.user.is_active:
            raise forms.ValidationError("This account is already active.")

TimeSyncPro/accounts/forms/custom_set_password_forms.py
from django import forms
from django.contrib.auth.forms import SetPasswordForm


class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.user.is_active:
            raise forms.ValidationError("This account is already active.")

TimeSyncPro/accounts/forms/delete_user_form.py
from django import forms


class DeleteUserForm(forms.Form):
    pass

TimeSyncPro/accounts/views/api_views.py
import logging
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import logout, get_user_model
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView
from TimeSyncPro.accounts.models import Profile
from TimeSyncPro.accounts.serializers import EmployeeSerializer
from TimeSyncPro.common.views_mixins import SmallPagination

logger = logging.getLogger(__name__)

UserModel = get_user_model()


class TeamEmployeesAPIView(generics.ListAPIView):
    permission_classes = [IsAuthenticated]
    authentication_classes = [SessionAuthentication]
    serializer_class = EmployeeSerializer
    pagination_class = SmallPagination

    def get_queryset(self):
        return (
            Profile.objects.filter(
                team_id=self.kwargs["pk"],
                team__company__slug=self.kwargs["company_slug"],
            )
            .select_related("user")
            .order_by("first_name")
        )


class ShiftEmployeesAPIView(generics.ListAPIView):
    permission_classes = [IsAuthenticated]
    authentication_classes = [SessionAuthentication]
    serializer_class = EmployeeSerializer
    pagination_class = SmallPagination

    def get_queryset(self):
        return (
            Profile.objects.filter(
                shift_id=self.kwargs["pk"],
                shift__company__slug=self.kwargs["company_slug"],
            )
            .select_related("user")
            .order_by("first_name")
        )


class DepartmentEmployeesAPIView(generics.ListAPIView):
    permission_classes = [IsAuthenticated]
    authentication_classes = [SessionAuthentication]
    serializer_class = EmployeeSerializer
    pagination_class = SmallPagination

    def get_queryset(self):
        return (
            Profile.objects.filter(
                department_id=self.kwargs["pk"],
                department__company__slug=self.kwargs["company_slug"],
            )
            .select_related("user")
            .order_by("first_name")
        )


class LogoutAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        try:
            logout(request)

            return Response(
                {"message": "Successfully logged out."}, status=status.HTTP_200_OK
            )
        except Exception as e:
            return Response(
                {"error": "Failed to logout. Please try again."},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

templates/accounts/activate_and_set_password.html
{% extends 'layout/layout.html' %}
{% load static %}
{% load filters %}
<!-- templates/accounts/activate_and_set_password.html -->

{% block style %}
    <link rel="stylesheet" href="{% static 'styles/pages/activate_account.css' %}">
{% endblock %}


{% block content %}
    <div class="activate_account">
        <h2>Set Password and Activate Your Account</h2>
        <form method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        <strong>Error:</strong> {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="part-form-container">

                {% for field in form %}
                    {% if not field.is_hidden %}

                        {% render_field field wrapper_class="form-row" class="form-control" label_class="form-label" %}
   
                    {% endif %}
                {% endfor %}
            </div>


            <button type="submit" class="default-btn">Activate</button>
        </form>
    </div>
{% endblock %}

templates/accounts/create_profile_and_company.html
{% extends "layout/layout.html" %}
{% load static %}
{% load filters %}
{% block style %}
    <link rel="stylesheet" href="{% static 'styles/pages/create-profile-company.css' %}">
{% endblock %}


{% block content %}
    <div class="profile-company-form-container">
        <form method="POST" enctype="multipart/form-data">
        {% include "partials/messages.html" %}
            {% csrf_token %}
            <div class="profile-company-form">
                <div class="profile-company-reg">
                    <div class="company-form reg-form">
                        <div class="part-form-container">
                            <h2>Company</h2>
                            <h4>Company Details</h4>
                            {% for field in company_form %}
                                {% render_field field wrapper_class="form-row" class="form-control" label_class="form-label" %}
                            {% endfor %}
                        </div>
                        <div class="part-form-container">
                            <h4>Company Address</h4>
                            {% for field in company_address_form %}
                                {% render_field field wrapper_class="form-row" class="form-control" label_class="form-label" %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="profile-form reg-form">
                        <div class="part-form-container">
                            <h2>Profile</h2>
                            <h4>Profile Details</h4>
                            {% for field in form %}
                                {% render_field field wrapper_class="form-row" class="form-control" label_class="form-label" %}
                            {% endfor %}
                        </div>
                        <div class="part-form-container">
                            <h4>Profile Address</h4>
                            {% for field in profile_address_form %}
                                {% render_field field wrapper_class="form-row" class="form-control" label_class="form-label" %}
                            {% endfor %}
                        </div>
                    </div>

                </div>
                <p class="required-fields-note">
                    <span class="required-star">*</span> Required fields
                </p>
                <button type="submit" class="btn submit-btn">Submit</button>
            </div>

        </form>
    </div>

{% endblock %}

templates/accounts/delete_employee.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>    #}
{#<meta charset="UTF-8">#}
{#    <title>Delete Team</title>#}
{#    <style>#}
{#        body {#}
{#            font-family: Arial, sans-serif;#}
{#        }#}
{#        .container {#}
{#            max-width: 600px;#}
{#            margin: 0 auto;#}
{#            padding: 20px;#}
{#            text-align: center;#}
{#            border: 1px solid #ccc;#}
{#            border-radius: 10px;#}
{#        }#}
{#        h1 {#}
{#            color: #d9534f;#}
{#        }#}
{#        .button-container {#}
{#            margin-top: 20px;#}
{#        }#}
{#        .button {#}
{#            padding: 10px 20px;#}
{#            margin: 0 10px;#}
{#            border: none;#}
{#            border-radius: 5px;#}
{#            cursor: pointer;#}
{#        }#}
{#        .button-yes {#}
{#            background-color: #d9534f;#}
{#            color: white;#}
{#        }#}
{#        .button-no {#}
{#            background-color: #5bc0de;#}
{#            color: white;#}
{#        }#}
{#    </style>#}
{#<body>#}
{#    <div class="container">#}
{#        <h1>Delete Team</h1>#}
{#        <p>Are you sure you want to delete the team "<strong>{{ user_to_delete.full_name }}</strong>"?</p>#}
{#        <p>This action cannot be undone.</p>#}
{#        <form method="post">#}
{#            {% csrf_token %}#}
{#            <div class="button-container">#}
{#                <button type="submit" class="button button-yes">Yes, delete it</button>#}
{#                <a href="{% url 'company_members'  company_slug=user.company.slug %}" class="button button-no">No, go back</a>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}
{#</body>#}
{#</html>#}

{% extends 'layout/company-layout.html' %}


{% block page-content %}
    <div class="content-area">
        <div class="profile-content">
            <div class="profile-main">
                <section class="profile-section delete-section">
                    <h2>Delete Employee</h2>
                    <h4>Are you sure you want to delete your employee "<strong>{{ object.profile.full_name }}</strong>"?</h4>
                    <h4 class="warning">This action cannot be undone.</h4>
                    <form method="post">
                        {% csrf_token %}
                        <div class="button-container">
                            <button type="submit" class="default-btn delete">Delete</button>
                            {% include "partials/cancel_btn_blue.html" %}
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/edit_profile.html
{% extends "layout/layout.html" %}
{% load filters %}

{% block content %}

    <div class="form-container">
        <h2>{{ form_title|default:"Form Title" }}</h2>

        <form action="{% url 'edit profile'  slug=user.slug %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

            {% for field in user_form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="error-message">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
            {% for field in additional_form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="error-message">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
            <div class="form-group">
                <input type="submit" value="{{ submit_text|default:'Submit' }}">
            </div>
        </form>
    </div>

    {#    {{ user_form.as_table }}#}
    {#    {% if additional_form %}#}
    {#      {{ additional_form.as_table }}#}
    {#    {% endif %}#}
    {#    <button type="submit">Save</button>#}
    {#    {% if user.is_company and user_to_edit == None %} }}#}
    {#    <a href="{% url 'delete company'  slug=user.slug company_name=user.get_company_name %}">Delete Company</a>#}
    {#    {% endif %}#}
    {#    {% csrf_token %}#}
    {#</form>#}
    {#    #}
{% endblock %}

templates/accounts/own_full_profile_edit.html
{% extends "layout/layout.html" %}

{% block content %}

{% load filters %}
    

<form action="{% url 'full edit profile' slug=user_to_edit.slug  %}" method="post" enctype="multipart/form-data">
    <table>
    {{ user_form.as_table }}
    {% if user_form.non_field_errors %}
        <div class="alert alert-danger">
            <ul>
                {% for error in user_form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    {% for field in user_form %}
        {% if field.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for error in field.errors %}
                        <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endfor %}

    {% if additional_form %}
        {{ additional_form.as_table }}
        {% if additional_form.non_field_errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for error in additional_form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% for field in additional_form %}
            {% if field.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for error in field.errors %}
                            <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    </table>
    <button type="submit">Save</button>
    {% csrf_token %}
</form>

{% endblock %}

templates/accounts/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>

</body>
</html>

templates/accounts/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
</form>

</body>
</html>

templates/accounts/signup_company_administrator.html
{% load static %}
{% load filters %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TimeSyncPro</title>
    <link rel="stylesheet" href="{% static 'styles/site.css' %}">
</head>

<body>

<div class="signup-container">
    <div class="signup-form-container">

        <div class="container-logo-login-signup" id="tsp-logo">

            <div class="container-logo-tsp" id="tsp-logo">
                <a href="{% url 'index' %}"><img src="{% static 'images/logo-blue.png' %}"
                                                 alt="TimeSyncPro"></a>
            </div>

        </div>

        <h2>Sign Up</h2>

        <form action="{% url 'sign_up_administrator' %}" method="post">
            {% csrf_token %}

            <div class="input-box">
                <span class="icon">
                <i class="fa-regular fa-envelope"></i>
        </span>
                {{ form.email }}
                <label for="id_email">Email address:</label>
            </div>

            <div class="input-box">
                <span class="icon">
                <i class="fa-solid fa-lock"></i>
        </span>
                {{ form.password1 }}
                <label for="id_password1">Password:</label>
            </div>

            <div class="input-box">
                <span class="icon">
                <i class="fa-solid fa-lock"></i>
        </span>
                {{ form.password2 }}
                <label for="id_password2">Confirm password:</label>
            </div>

{#            <div class="input-box">#}
{#                <span class="icon">#}
{#          <i class="fa-regular fa-user"></i>#}
{#        </span>#}
{#                {{ form.first_name }}#}
{#                <label for="id_first_name">First name:</label>#}
{##}
{#            </div>#}
{##}
{#            <div class="input-box">#}
{#                <span class="icon">#}
{#          <i class="fa-regular fa-user"></i>#}
{#        </span>#}
{#                {{ form.last_name }}#}
{#                <label for="id_last_name">Last name:</label>#}
{##}
{#            </div>#}

{#            <div class="input-box">#}
{#                <span class="icon">#}
{#          <i class="fa-regular fa-building"></i>#}
{#        </span>#}
{#                {{ form.name }}#}
{#                <label for="id_company_name">Company name:</label>#}
{#            </div>#}


            <button class="sign-up-button sign-up" type="submit">Register</button>

            <div class="register-link">
                <p>Already a member? <a href="{% url 'sign_in' %}">Log in</a></p>
            </div>

        </form>
    </div>
</div>
</body>
<script src="{% static 'js/signup-login.js' %}"></script>
</html>